services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: assinat-streams-app
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    env_file:
      - .env
  mysql:
    image: mysql:8.0
    container_name: assinat-streams-db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: